language: node_js
node_js:
- '4'
env:
  matrix:
  - TASK=lint
  - TASK=unittest GUI=1
  - TASK=servertest
cache:
  directories:
  - node_modules
before_install:
- npm install -g npm@3
- npm --version
before_script:
- if [ $GUI ]; then export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start && sleep 3; fi
script:
- npm run $TASK
- tox -e discopane-ui-tests -- --base-url http://localhost:4000
addons:
  firefox: latest
